### ISSUE TITLE
一千五百万零三百零一

### ISSUE THREAD

**Issue by ChisenZhang** [kinggreenhall/cn2an#1]
一千五百万零三百零一 => 1005000301

**Comment by kinggreenhall** [comment]
谢谢反馈，我会尽快修复的～

**Comment by kinggreenhall** [comment]
已修复，请更新至 v0.0.7。

![image](https://user-images.githubusercontent.com/7982046/50531160-9230e080-0b40-11e9-860f-faec169d5c0f.png)
